download:
	rm -rf Godeps vendor
	godep save ./...
	godep go install ./...
upgrade:
	rm -rf Godeps vendor
	go get -u ./...
	godep save ./...
	godep go install ./...
install:
	godep go install ./...
generate:
	go generate ./services/... ./shared/...
build:
	godep go build -o app
build-linux:
	CGO_ENABLED=0 GOOS=linux godep go build -a -installsuffix cgo -o app .
run:
	godep go run main.go
